### ISSUE TITLE
ModuleNotFoundErrors after fresh install in venv

### ISSUE THREAD

**Issue by onenetworkguy** [afourmy/e-napalm#10]
## Issue
Received two `ModuleNotFoundErrors` after installation:

```
ModuleNotFoundError: No module named 'flask_wtf'
```

```
ModuleNotFoundError: No module named 'napalm_base'
```

## Resolution

* Installed `flask-wtf` integration:

```
pip install flask-wtf
```

* Renamed `napalm_base` to `napalm` on line 1 in models.py

## Recommended Solution

* Add `flask-wtf` to requirements.txt
* Rename `napalm_base` to `napalm` in models.py

**Comment by afourmy** [comment]
Thank you for contributing !
